# net_w5500
CONFIG_NET_W5500=y
CONFIG_NET_W5500_IP_DHCP=y
CONFIG_NET_W5500_PING_TARGET="192.168.10.1"

# my_cli
CONFIG_MY_CLI=y

# net_w5500_led
CONFIG_NET_W5500_LED=y

# Network
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_DHCPV4=y

# W5500 via SPI (Ethernet)
CONFIG_SPI=y
CONFIG_ETH_W5500=y

# General
CONFIG_REBOOT=y
CONFIG_LOG=y
CONFIG_NET_LOG=y
